// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRO8IX-vU59RM-BtHR-aKYzBdA4Tq4nhA',
    appId: '1:267613378001:web:60bba8114dc843fafcfcf0',
    messagingSenderId: '267613378001',
    projectId: 'evesafe-53dce',
    authDomain: 'evesafe-53dce.firebaseapp.com',
    storageBucket: 'evesafe-53dce.appspot.com',
    measurementId: 'G-SYQ5CR2WLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFXtrcx4sl8CWd8CM3Qv1jeItVwRJihc',
    appId: '1:267613378001:android:a0902b8a7fb3449dfcfcf0',
    messagingSenderId: '267613378001',
    projectId: 'evesafe-53dce',
    storageBucket: 'evesafe-53dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMpqGC007eInpmoG1RXH8i729jmgTOKU',
    appId: '1:267613378001:ios:175fee504c3f3568fcfcf0',
    messagingSenderId: '267613378001',
    projectId: 'evesafe-53dce',
    storageBucket: 'evesafe-53dce.appspot.com',
    iosClientId: '267613378001-l0a55otus02t3gdr5r7dhlqjf521tiqd.apps.googleusercontent.com',
    iosBundleId: 'com.yadav.ayush.evesafe.womensafety',
  );
}
